language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Get my folder
  - my_github=${PWD##*/}  
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # Build Unreal Engine 4 in a folder at the same depth, must be user with a Epic Games account connect to a GitHub
  - git config --global user.email "richel@richelbilderbeek.nl"
  - git config --global user.name "richelbilderbeek"
  - cd ..
  - git clone https://github.com/EpicGames/UnrealEngine.git
  - cd UnrealEngine
  - ./Setup.sh
  - ./GenerateProjectFiles.sh
  - make
  - cd $my_github

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14_ue4
